version: '3.7'

services:

  zookeeper-1:
    image: zookeeper:3.4.9
    hostname: zookeeper-1
    container_name: zookeeper-1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper-1:2188:3188
    networks:
      - dart-network

  kafka-broker-1:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka-broker-1
    container_name: kafka-broker-1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO"
      KAKFA_LISTENERS: LISTENER_LOCALHOST://kafka-broker-1:9092,DOCKER_INTERNAL://kafka-broker-1:19092,EXTRNALAUTH://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: LISTENER_LOCALHOST://kafka-broker-1:9092,DOCKER_INTERNAL://kafka-broker-1:19092,EXTRNALAUTH://localhost:9093
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_LOCALHOST:PLAINTEXT,DOCKER_INTERNAL:PLAINTEXT,EXTRNALAUTH:SASL_PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181"
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.auth.SimpleAclAuthorizer"
      KAFKA_LISTENER_NAME_EXTRNALAUTH_PLAIN_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required user_eidos=\"eidos-pass\";"
      READERS: eidos
      TOPIC: stream.out
      KAFKA_SUPER_USERS: User:admin;User:ANONYMOUS
    networks:
      - dart-network

  auto-topic-provisioner:
    image: twosixlabsdart/auto-topic-provisioner:latest
    container_name: auto-topic-provisioner
    hostname: auto-topic-provisioner
    depends_on:
      - kafka-broker-1
    volumes:
      - ./topics.yml:/opt/config/topics.yml
    networks:
      - dart-network

networks:
  dart-network: