default_base_dir="../corpora/loop"

# Coordinate servers
REST_CONSUMER_SERVICE=https://${REST_HOSTNAME:-localhost}/dart/api/v1/cdrs
REST_PRODUCER_SERVICE=https://${REST_HOSTNAME:-localhost}/dart/api/v1/readers/upload

# Coordinate credentials.
REST_CONSUMER_USERNAME="${EIDOS_USERNAME}"
REST_CONSUMER_PASSWORD="${EIDOS_PASSWORD}"
REST_PRODUCER_USERNAME="${EIDOS_USERNAME}"
REST_PRODUCER_PASSWORD="${EIDOS_PASSWORD}"
CURL_PRODUCER_USERNAME="${EIDOS_USERNAME}"
CURL_PRODUCER_PASSWORD="${EIDOS_PASSWORD}"
KAFKA_USERNAME="${EIDOS_USERNAME}"
KAFKA_PASSWORD="${EIDOS_PASSWORD}"

# Coordinate directories.
EIDOS_BASE_DIR="${EIDOS_BASE_DIR:-$default_base_dir}"
EIDOS_INPUT_SUBDIR="${EIDOS_INPUT_SUBDIR:-input}"
EIDOS_OUTPUT_SUBDIR="${EIDOS_OUTPUT_SUBDIR:-output}"
DONE_SUBDIR="${DONE_SUBDIR:-done}"
KAFKA_SUBDIR="${KAFKA_SUBDIR:-kafka}"

# Set up the pipeline.

# For kafka, input comes from the network.
KAFKA_CONSUMER_OUTPUT_DIR="${KAFKA_CONSUMER_OUTPUT_DIR:-$EIDOS_BASE_DIR/$EIDOS_INPUT_SUBDIR/$KAFKA_SUBDIR}"

REST_CONSUMER_INPUT_DIR="${REST_CONSUMER_INPUT_DIR:-$KAFKA_CONSUMER_OUTPUT_DIR}"
REST_CONSUMER_OUTPUT_DIR="${REST_CONSUMER_OUTPUT_DIR:-$EIDOS_BASE_DIR/$EIDOS_INPUT_SUBDIR}"
REST_CONSUMER_DONE_DIR="${REST_CONSUMER_DONE_DIR:-$REST_CONSUMER_INPUT_DIR/$DONE_SUBDIR}"

EIDOS_INPUT_DIR="${EIDOS_INPUT_DIR:-$REST_CONSUMER_OUTPUT_DIR}"
EIDOS_OUTPUT_DIR="${EIDOS_OUTPUT_DIR:-$EIDOS_BASE_DIR/$EIDOS_OUTPUT_SUBDIR}"
EIDOS_DONE_DIR="${EIDOS_DONE_DIR:-$EIDOS_INPUT_DIR/$DONE_SUBDIR}"

# For the rest producer, output goes to the network.
REST_PRODUCER_INPUT_DIR="${REST_PRODUCER_INPUT_DIR:-$EIDOS_OUTPUT_DIR}"
REST_PRODUCER_DONE_DIR="${REST_PRODUCER_DONE_DIR:-$REST_PRODUCER_INPUT_DIR/$DONE_SUBDIR}"
