default_base_dir="../corpora/loop"

# Coordinate everything.
EIDOS_BASE_DIR="${EIDOS_BASE_DIR:-$default_base_dir}"
EIDOS_INPUT_SUBDIR="${EIDOS_INPUT_SUBDIR:-input}"
EIDOS_OUTPUT_SUBDIR="${EIDOS_OUTPUT_SUBDIR:-output}"
DONE_SUBDIR="${DONE_SUBDIR:-done}"
KAFKA_SUBDIR="${DONE_SUBDIR:-kafka}"

# Set up the pipeline.

# For kafka, input comes from the network.
KAFKA_CONSUMER_OUTPUT_DIR="${KAFKA_CONSUMER_OUTPUT_DIR:-$EIDOS_BASE_DIR/$EIDOS_INPUT_SUBDIR/$KAFKA_SUBDIR}"

REST_CONSUMER_INPUT_DIR="${REST_CONSUMER_INPUT_DIR:-$KAFKA_CONSUMER_OUTPUT_DIR}"
REST_CONSUMER_OUTPUT_DIR="${REST_CONSUMER_OUTPUT_DIR:-$EIDOS_BASE_DIR/$EIDOS_INPUT_SUBDIR}"
REST_CONSUMER_DONE_DIR="${REST_CONSUMER_DONE_DIR:-$REST_CONSUMER_INPUT_DIR/$DONE_SUBDIR}"

EIDOS_INPUT_DIR="${EIDOS_INPUT_DIR:-$REST_CONSUMER_OUTPUT_DIR}"
EIDOS_OUTPUT_DIR="${EIDOS_OUTPUT_DIR:-$EIDOS_BASE_DIR/$EIDOS_OUTPUT_SUBDIR}"
EIDOS_DONE_DIR="${EIDOS_DONE_DIR:-EIDOS_INPUT_DIR/$DONE_SUBDIR}"

# For the rest producer, output goes to the network.
REST_PRODUCER_INPUT_DIR="${REST_PRODUCER_INPUT_DIR:-$EIDOS_OUTPUT_DIR}"
REST_PRODUCER_DONE_DIR="${REST_PRODUCER_DONE_DIR:-REST_PRODUCER_INPUT_DIR/$DONE_SUBDIR}"
