openapi: 3.0.0
servers:
  - url: 'http://localhost:9000/eidos/v2'
    description: Localhost
  - url: 'http://kwalcock.noip.me/eidos/v2'
    description: Keith's computer
info:
  title: eidos
  version: v2
paths:
  /ping:
    get:
      responses:
        '200':
          description: OK
  /status:
    get:
      responses:
        '200':
          description: OK
  /read:
    post:
      summary: Read (process) a simple text
      responses:
        default:
          description: Default error sample response
          
