version: '3.4'

services:
  eidos:
    container_name: eidos
    hostname: eidos
    image: clulab/eidos-loop
    environment:
      # Run export.sh before using this.
      KAFKA_CONSUMER_BOOTSTRAP_SERVERS: ${KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
      KAFKA_APP_TOPIC: ${KAFKA_APP_TOPIC}

      REST_HOSTNAME: ${REST_HOSTNAME}

      EIDOS_USERNAME: ${EIDOS_USERNAME}
      EIDOS_PASSWORD: ${EIDOS_PASSWORD}

      EIDOS_BASE_DIR: /eidos

      EIDOS_MEMORY: -Xmx20g
      EIDOS_THREADS: 4

      # Another possibility is earliest.  Use latest for OIAD (Ontology In A Day).
      KAFKA_CONSUMER_AUTO_OFFSET_RESET: latest
    networks:
      - readers-net

networks:
  readers-net: