---
triggers:
  - season
  - meher
  - afrasa
  - belg
  - belgi
  - dada
  - deyr
  - diraac
  - gana
  - gu
  - hagaya
  - heys
  - karma
  - keren
  - kremt
  - kremti
  - sugum
---
'444179':
    crop:
      end: 1
      start: 9
    sugum:
      end: 5
      start: 4
    short rainy:
      end: 5
      start: 4
    harvest:
      end: 1
      start: 9
    hunger:
      end: 3
      start: 12
    karma:
      end: 9
      start: 6
    meher:
      end: 9
      start: 6
    long rainy:
      end: 9
      start: 6
    planting:
      end: 9
      start: 6
'444180':
    crop:
      end: 1
      start: 9
    harvest:
      end: 1
      start: 9
    hunger:
      end: 10
      start: 6
    kremti:
      end: 9
      start: 6
    long rainy:
      end: 9
      start: 6
    planting:
      end: 9
      start: 6
    belgi:
      end: 5
      start: 4
    short rainy:
      end: 5
      start: 4
'444181':
    crop:
      end: 1
      start: 9
    harvest:
      end: 1
      start: 9
    hunger:
      end: 3
      start: 12
    planting:
      end: 9
      start: 6
    kremt:
      end: 10
      start: 6
    rainy:
      end: 10
      start: 6
'444183':
    crop:
      end: 1
      start: 9
    harvest:
      end: 1
      start: 9
    hunger:
      end: 6
      start: 2
    planting:
      end: 9
      start: 6
    kremt:
      end: 10
      start: 6
    rainy:
      end: 10
      start: 6
'444185':
    crop:
      end: 8
      start: 2
    gana:
      end: 5
      start: 4
    first rainy:
      end: 5
      start: 4
    harvest:
      end: 8
      start: 2
    hunger:
      end: 3
      start: 12
    long rainy:
      end: 9
      start: 6
    planting:
      end: 4
      start: 2
    hagaya:
      end: 11
      start: 10
    second rainy:
      end: 11
      start: 10
    short rainy:
      end: 5
        start: 4
'444186':
    crop:
      end: 8
      start: 2
    first rainy:
      end: 5
      start: 4
    short rainy:
      end: 5
      start: 4
    harvest:
      end: 8
      start: 2
    hunger:
      end: 3
      start: 12
    long rainy:
      end: 9
      start: 6
    planting:
      end: 4
      start: 2
    second rainy:
      end: 11
      start: 10
'444187':
    crop:
      end: 1
      start: 9
    harvest:
      end: 1
      start: 9
    hunger:
      end: 10
      start: 6
    long rainy:
      end: 9
      start: 6
    planting:
      end: 9
      start: 6
    short rainy:
      end: 5
      start: 4
'444188':
    crop:
      end: 1
      start: 9
    harvest:
      end: 1
      start: 9
    hunger:
      end: 6
      start: 2
    planting:
      end: 9
      start: 6
    kremt:
      end: 10
      start: 6
    rainy:
      end: 10
      start: 6
