---
early: -1
premature: -1
delayed: 1
late: 1
---
triggers:
  - afrasa
  - belg
  - belgi
  - dada
  - deyr
  - gana
  - gu
  - hagaya
  - heys
  - karma
  - keren
  - kiremt
  - kremt
  - kremti
  - meher
  - season
  - sugum
---
'337996': # Ethiopia
  belg:
    start: 5
    end: 8
  crop:
    start: 2
    end: 8
  dry:
    start: 1
    end: 3
  gana:
    start: 4
    end: 5
  hagaya:
    start: 10
    end: 11
  harvest:
    start: 9
    end: 12
  hunger:
    start: 1
    end: 4
  karma:
    start: 6
    end: 9
  kiremt:
    start: 6
    end: 9
  kremt:
    start: 6
    end: 9
  lean:
    start: 1
    end: 4
  long rainy:
    start: 6
    end: 9
  meher:
    start: 9
    end: 2
  planting:
    start: 6
    end: 9
  short rainy:
    start: 3
    end: 5
'444179': # Afar
  belg:
    start: 4
    end: 5
  crop:
    start: 6
    end: 1
  dry:
    start: 1
    end: 3
  harvest:
    start: 9
    end: 1
  hunger:
    start: 1
    end: 4
  karma:
    start: 6
    end: 9
  kiremt:
    start: 6
    end: 9
  kremt:
    start: 6
    end: 9
  lean:
    start: 1
    end: 3
  long rainy:
    start: 6
    end: 9
  meher:
    start: 9
    end: 2
  planting:
    start: 6
    end: 9
  short rainy:
    start: 4
    end: 5
  sugum:
    start: 4
    end: 5
'444180': # Amhara
  belg:
    start: 4
    end: 5
  crop:
    start: 6
    end: 1
  dry:
    start: 1
    end: 3
  harvest:
    start: 9
    end: 1
  hunger:
    start: 6
    end: 10
  kiremt:
    start: 6
    end: 9
  kremt:
    start: 6
    end: 9
  lean:
    start: 6
    end: 10
  long rainy:
    start: 6
    end: 9
  meher:
    start: 9
    end: 2
  planting:
    start: 6
    end: 9
  short rainy:
    start: 4
    end: 5
'444181': # Benishangul
  crop:
    start: 6
    end: 1
  dry:
    start: 1
    end: 3
  harvest:
    start: 9
    end: 1
  hunger:
    start: 1
    end: 3
  kiremt:
    start: 6
    end: 10
  kremt:
    start: 6
    end: 10
  lean:
    start: 12
    end: 3
  meher:
    start: 9
    end: 2
  planting:
    start: 6
    end: 9
  rain:
    start: 6
    end: 10
  rainy:
    start: 6
    end: 10
'444183': # Gambela
  crop:
    start: 6
    end: 1
  dry:
    start: 1
    end: 3
  harvest:
    start: 9
    end: 1
  hunger:
    start: 2
    end: 6
  kiremt:
    start: 6
    end: 10
  kremt:
    start: 6
    end: 10
  lean:
    start: 2
    end: 6
  meher:
    start: 9
    end: 2
  planting:
    start: 6
    end: 9
  rain:
    start: 6
    end: 10
  rainy:
    start: 6
    end: 10
'444185': # Oromia
  belg:
    start: 4
    end: 5
  crop:
    start: 2
    end: 8
  dry:
    start: 1
    end: 3
  gana:
    start: 4
    end: 5
  hagaya:
    start: 10
    end: 11
  harvest:
    start: 4
    end: 8
  hunger:
    start: 1
    end: 4
  kiremt:
    start: 6
    end: 10
  kremt:
    start: 6
    end: 10
  lean:
    start: 1
    end: 4
  meher:
    start: 9
    end: 2
  planting:
    start: 2
    end: 4
  rain:
    start: 4
    end: 5
  rainy:
    start: 4
    end: 5
'444186': # Somali
  belg:
    start: 4
    end: 5
  crop:
    start: 2
    end: 8
  deyr:
    start: 10
    end: 11
  dry:
    start: 1
    end: 3
  gu:
    start: 4
    end: 5
  harvest:
    start: 4
    end: 8
  hunger:
    start: 1
    end: 4
  lean:
    start: 1
    end: 4
  meher:
    start: 9
    end: 2
  planting:
    start: 2
    end: 4
  rain:
    start: 4
    end: 5
  rainy:
    start: 4
    end: 5
'444187': # Tigray
  belg:
    start: 4
    end: 5
  belgi:
    start: 4
    end: 5
  crop:
    start: 6
    end: 1
  dry:
    start: 1
    end: 3
  harvest:
    start: 9
    end: 1
  hunger:
    start: 6
    end: 10
  kiremt:
    start: 6
    end: 9
  kremt:
    start: 6
    end: 9
  kremti:
    start: 6
    end: 9
  lean:
    start: 6
    end: 10
  long rainy:
    start: 6
    end: 9
  meher:
    start: 9
    end: 2
  planting:
    start: 6
    end: 9
  short rainy:
    start: 4
    end: 5
  rain:
    start: 4
    end: 5
  rainy:
    start: 4
    end: 5
'444188': # SNNPR
  belg:
    start: 6
    end: 10
  crop:
    start: 6
    end: 1
  dry:
    start: 1
    end: 3
  harvest:
    start: 9
    end: 1
  hunger:
    start: 2
    end: 6
  kiremt:
    start: 6
    end: 10
  kremt:
    start: 6
    end: 10
  lean:
    start: 2
    end: 6
  meher:
    start: 9
    end: 2
  planting:
    start: 6
    end: 9
  rain:
    start: 6
    end: 10
  rainy:
    start: 6
    end: 10
